blank_issues_enabled: false
contact_links:
  - name: Aniyomi help discord
    url: https://discord.gg/F32UjdJZrR
    about: Common questions are answered here.
  - name: Aniyomi extensions GitHub repository
    url: https://github.com/jmir1/aniyomi-extensions
    about: Issues about an anime extension/source/catalogue should be opened here instead.
